% dinâmica das malhas de movimento horizontal

function dinamica = obterMalhaHorizontal(controlador, controladorTheta, planta)

s = tf('s');
numerador = planta.g * controlador.Ki * controladorTheta.Kp;
denominador = planta.J * s^5 + controladorTheta.Kd * s^4 + ...
    controladorTheta.Kp * s^3 + ...
    planta.g * controladorTheta.Kp * ...
    controlador.Kd * s^2 + ...
    planta.g * controladorTheta.Kp * controlador.Kp * s ...
    + planta.g * controladorTheta.Kp * controlador.Ki;
dinamica = numerador / denominador;
end