% dinâmica das malhas de movimento horizontal

function dinamica = obterMalhaHorizontal(controlador, controladorTheta, planta)

s = tf('s');
numerador = planta.g * controlador.Ki * controladorTheta.Kp * controladorTheta.Kv;
denominador = planta.J * s^5 + controladorTheta.Kv * s^4 + ...
    controladorTheta.Kp * controladorTheta.Kv * s^3 + ...
    planta.g * controladorTheta.Kp * controladorTheta.Kv * ...
    controlador.Kd * s^2 + ...
    planta.g * controladorTheta.Kp * controladorTheta.Kv * controlador.Kp * s ...
    + planta.g * controladorTheta.Kp * controladorTheta.Kv * controlador.Ki;
dinamica = numerador / denominador;

end